GET http://localhost:5000/users/id/transactions
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJjcmVhdGl2ZWZuIiwidXNlcklkIjoyLCJyb2xlIjoiY3JlYXRvciIsImxhc3ROYW1lIjoiY3JlYXRpdmVsbiIsImF2YXRhciI6ImFub24ucG5nIiwiZGlzcGxheU5hbWUiOiJjcmVhdGl2ZWRuIiwiYmFsYW5jZSI6IjQ1IiwiZW1haWwiOiJjcmVhdGl2ZUBnbWFpbC5jb20iLCJyYXRpbmciOjMsImlhdCI6MTc3OTQ1NDc1MSwiZXhwIjoxNzc5NDU4MzUxfQ.8GoHWq74oOaQy9q9BXAjUSyNhLoszwu9Hd4G9XNMcp4